<script setup lang="ts">
import { CheckCircle2, Cloud, Copy, Database, ExternalLink, RefreshCw, ShieldAlert, Video } from 'lucide-vue-next';
import { ElMessage } from 'element-plus';

definePageMeta({ layout: 'admin' });
const api = useAdminApi();
const { data, status, refresh } = await useAsyncData('admin-real-connection', () => api.getConnection());
const copyValue = async (value: string) => { await navigator.clipboard.writeText(value); ElMessage.success('已复制'); };
const webhookUrl = computed(() => import.meta.client ? `${window.location.origin}/api/paypal/webhook` : '/api/paypal/webhook');
</script>

<template>
  <div>
    <AdminPageHeader title="Cloudflare 与支付" description="只读检查生产数据链路；密钥必须通过 Cloudflare Secrets 配置，后台不回显。"><el-button :loading="status === 'pending'" @click="() => refresh()"><RefreshCw :size="16" />重新检测</el-button></AdminPageHeader>
    <section class="connection-banner" :class="data?.cloudflare.database && data?.paypal.connected ? 'is-ok' : 'is-warning'"><span><CheckCircle2 v-if="data?.cloudflare.database && data?.paypal.connected" :size="22" /><ShieldAlert v-else :size="22" /></span><div><strong>{{ data?.cloudflare.database && data?.paypal.connected ? '真实数据链路已连接' : '生产数据链路尚未完成' }}</strong><p>{{ data ? `检查时间 ${new Date(data.checkedAt).toLocaleString('zh-CN', { hour12: false })}` : '正在检测 Cloudflare D1 和 PayPal API' }}</p></div></section>
    <div class="connection-grid">
      <section class="admin-panel connection-panel"><div class="admin-panel__header"><div><h2>Cloudflare D1</h2><p>播放事件、订单、权益和 Webhook 幂等记录</p></div><el-tag :type="data?.cloudflare.database ? 'success' : 'danger'">{{ data?.cloudflare.database ? '已连接' : '未连接' }}</el-tag></div><div class="connection-check"><span><Database :size="18" />数据库查询</span><strong :class="data?.cloudflare.database ? 'success-text' : 'danger-text'">{{ data?.cloudflare.database ? '正常' : data?.cloudflare.databaseError || '失败' }}</strong></div><div class="connection-check"><span>连接方式</span><strong>{{ data?.cloudflare.mode || '检测中' }}</strong></div><div class="connection-check"><span>Account ID</span><strong>{{ data?.cloudflare.accountConfigured || data?.cloudflare.mode === 'D1 binding' ? '已配置' : '缺失' }}</strong></div><div class="connection-check"><span>D1 Database ID</span><strong>{{ data?.cloudflare.databaseConfigured || data?.cloudflare.mode === 'D1 binding' ? '已配置' : '缺失' }}</strong></div><div class="connection-check"><span>API Token</span><strong>{{ data?.cloudflare.apiTokenConfigured || data?.cloudflare.mode === 'D1 binding' ? '已加密配置' : '缺失' }}</strong></div></section>
      <section class="admin-panel connection-panel"><div class="admin-panel__header"><div><h2>PayPal Checkout</h2><p>官方 Orders API、Capture 与 Webhook 验签</p></div><el-tag :type="data?.paypal.connected ? 'success' : 'danger'">{{ data?.paypal.connected ? '已连接' : '未连接' }}</el-tag></div><div class="connection-check"><span><Cloud :size="18" />API 环境</span><strong>{{ data?.paypal.environment || 'sandbox' }}</strong></div><div class="connection-check"><span>Client ID / Secret</span><strong :class="data?.paypal.connected ? 'success-text' : 'danger-text'">{{ data?.paypal.connected ? '验证成功' : data?.paypal.error || '缺失' }}</strong></div><div class="connection-check"><span>Webhook ID</span><strong>{{ data?.paypal.webhookConfigured ? '已配置' : '缺失' }}</strong></div><div class="connection-check"><span>最近 Webhook</span><strong>{{ data?.paypal.lastWebhookAt ? new Date(data.paypal.lastWebhookAt).toLocaleString('zh-CN', { hour12: false }) : '暂无已验证回调' }}</strong></div><div class="connection-copy"><code>{{ webhookUrl }}</code><button type="button" title="复制 Webhook URL" @click="copyValue(webhookUrl)"><Copy :size="15" /></button></div></section>
      <section class="admin-panel connection-panel"><div class="admin-panel__header"><div><h2>Cloudflare 媒体分发</h2><p>R2/Stream HLS 地址与短期播放签名</p></div><el-tag :type="data?.cloudflare.mediaConfigured ? 'success' : 'warning'">{{ data?.cloudflare.mediaConfigured ? '已配置' : '待配置' }}</el-tag></div><div class="connection-feature"><Video :size="23" /><div><strong>签名播放地址</strong><span>每次播放由服务端校验 D1 权益，再生成 10 分钟 HMAC URL。</span></div></div><div class="connection-check"><span>CLOUDFLARE_MEDIA_BASE_URL</span><strong>{{ data?.cloudflare.mediaConfigured ? '已配置' : '缺失' }}</strong></div><div class="connection-check"><span>MEDIA_SIGNING_SECRET</span><strong>{{ data?.cloudflare.mediaConfigured ? '已加密配置' : '缺失' }}</strong></div></section>
      <section class="admin-panel connection-panel"><div class="admin-panel__header"><div><h2>上线步骤</h2><p>生产环境只需完成一次</p></div></div><ol class="deployment-steps"><li><span>1</span><div><strong>创建 D1 并执行迁移</strong><code>migrations/0001_reelnova_core.sql</code></div></li><li><span>2</span><div><strong>绑定数据库为 DB</strong><small>Cloudflare Pages / Worker 设置 → Bindings</small></div></li><li><span>3</span><div><strong>添加 PayPal 与媒体 Secrets</strong><small>不要使用普通明文环境变量保存 Secret</small></div></li><li><span>4</span><div><strong>在 PayPal 注册 Webhook URL</strong><small>订阅 PAYMENT.CAPTURE.COMPLETED 等事件</small></div></li></ol><a class="el-button" href="https://dash.cloudflare.com/" target="_blank" rel="noreferrer">打开 Cloudflare<ExternalLink :size="15" /></a></section>
    </div>
  </div>
</template>
